FROM elasticsearch:7.6.2
MAINTAINER whb whbjzzwjxq@gmail.com
EXPOSE 9200 9300
COPY es-plugins /usr/share/elasticsearch/plugins/
VOLUME /root/volume/elasticsearch/data /usr/share/elasticsearch/data
VOLUME /root/volume/elasticsearch/log /usr/share/elasticsearch/log